In [1]:
# GAILを用いて、cameleon-gymの環境で学習する

import gymnasium as gym
import cameleon_gym_env
import time
import numpy as np
from imitation.policies.serialize import load_policy
from imitation.util.util import make_vec_env
from imitation.data.wrappers import RolloutInfoWrapper
from imitation.data import rollout
from imitation.algorithms.adversarial.gail import GAIL
from imitation.rewards.reward_nets import BasicRewardNet
from imitation.util.networks import RunningNorm
from stable_baselines3 import PPO
from stable_baselines3.ppo import MlpPolicy
from stable_baselines3.common.evaluation import evaluate_policy

In [2]:
import pickle


SEED = 42

env = make_vec_env(
    "Cameleon-v0",
    rng=np.random.default_rng(SEED),
    n_envs=8,
    post_wrappers=[
        lambda env, _: RolloutInfoWrapper(env)
    ],  # needed for computing rollouts later
)
env_file_path = env.__module__
print(env_file_path)

print("observation")
print(env.observation_space)

path_file = "/media/gaia-22/ESD-ISO/auto_cosmos/cameleon/data/pkl/rollout03.pkl"
rollouts = pickle.load(open(path_file, 'rb'))


rng = np.random.default_rng()

rolloutee = rollout.rollout(
    None,
    env,
    rollout.make_sample_until(min_timesteps=None, min_episodes=50),
    rng=rng,
)

print(rolloutee)

print("nexting")
 

stable_baselines3.common.vec_env.dummy_vec_env
observation
Box([[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], [[2.5500000e+02 2.5500000e+02 2.5500000e+02 ... 2.5500000e+02
  2.5500000e+02 2.5500000e+02]
 [2.5500000e+02 2.5500000e+02 2.5500000e+02 ... 2.5500000e+02
  2.5500000e+02 2.5500000e+02]
 [2.5500000e+02 2.5500000e+02 2.5500000e+02 ... 2.5500000e+02
  2.5500000e+02 2.5500000e+02]
 ...
 [2.5500000e+02 2.5500000e+02 2.5500000e+02 ... 2.5500000e+02
  2.5500000e+02 2.5500000e+02]
 [2.5500000e+02 2.5500000e+02 2.5500000e+02 ... 2.5500000e+02
  2.5500000e+02 2.5500000e+02]
 [1.0000000e+01 1.0000000e+01 1.0000000e+01 ... 3.4028235e+38
  3.4028235e+38 3.4028235e+38]], (241, 240), float32)
[TrajectoryWithRew(obs=array([[[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0. 

In [ ]:
learner = PPO(
    env=env,
    policy=MlpPolicy,
    batch_size=64,
    ent_coef=0.0,
    learning_rate=0.0004,
    gamma=0.95,
    n_epochs=5,
    seed=SEED,
)
reward_net = BasicRewardNet(
    observation_space=env.observation_space,
    action_space=env.action_space,
    normalize_input_layer=RunningNorm,
)
gail_trainer = GAIL(
    demonstrations=rolloutee,
    demo_batch_size=64,
    gen_replay_buffer_capacity=512,
    n_disc_updates_per_round=8,
    venv=env,
    gen_algo=learner,
    reward_net=reward_net,
)

learner_rewards_before_training, _ = evaluate_policy(
    learner, env, 100, return_episode_rewards=True
)



In [ ]:
env.seed(SEED)
gail_trainer.train(20)

env.seed(SEED)
learner_rewards_after_training, _ = evaluate_policy(
    learner, env, 100, return_episode_rewards=True
)

print(
    "Rewards before training:",
    np.mean(learner_rewards_before_training),
    "+/-",
    np.std(learner_rewards_before_training),
)
print(
    "Rewards after training:",
    np.mean(learner_rewards_after_training),
    "+/-",
    np.std(learner_rewards_after_training),
)
